### ISSUE TITLE
Complete all Snusbase API Calls

### ISSUE THREAD

**Issue by shaivilp** [hiibolt/dykm#4]
Create the (three) helper functions for each respective Snusbase section. 

All three go in each of their respective files (`api_snusbase_query.go`, `api_snusbase_geolocation.go`, and `api_snusbase_hashing.go`)

- [x] `snusbase_query` can take any of the following: `email | username | hash | ip | name | password`
- [x] `snusbase_hashing` can take either of the following: `hash | password`
- [x] `snusbase_geolocation` can only ever take `ip`

The two functions with multiple PII types must take two argumenst: the PII type you are giving it (use the PIIType enum) and the PII itself.

The Snusbase Geolocation API does not support anything but IP, so it's not necessary to specify the type and accordingly will only have one argument.

**Comment by hiibolt** [comment]
Example for making a call to the OSINT backend:
```bash
curl \
--header 'Authorization: aGlpYm9sdHByaW1hcnlrZXltZW93' \
-d 'example@gmail.com' \
-X POST \
https://osint.hiibolt.com/api/snusbase_query/email
```

**Comment by hiibolt** [comment]
Nicely done!
